[actions] Add linters job

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -3,6 +3,65 @@ name: build_and_test
 on: [push]
 
 jobs:
+  lint:
+    runs-on: ubuntu-latest
+
+    steps:
+    - uses: actions/checkout@v2
+
+    - name: Apt Installs
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y python3 python3-pip shellcheck
+
+    - name: Pip Install
+      run: |
+        pip3 install setuptools wheel
+        pip3 install virtualenv
+        python3 -m virtualenv checkenv
+        source checkenv/bin/activate
+        pip3 install cogapp pycodestyle
+
+    - name: Check Cog
+      run: |
+        # Check that we re-ran cog as needed
+        set -ex
+        source checkenv/bin/activate
+        export PYTHONPATH=.
+        cog -r `find -name "*.c"` `find -name "*.cpp"` `find -name "*.h"` `find -name "*.yml"`
+        # See if anything changed
+        git diff > /tmp/cog.diff
+        cat /tmp/cog.diff
+        # Reset for next check
+        git checkout .
+        # Fail the stage so we know to re-run cog
+        ! test -s /tmp/cog.diff
+
+    - name: Clang Format
+      run: |
+        # Check that we ran clang-format
+        set -ex
+        clang-format -i `find -name "*.c"` `find -name "*.cpp"` `find -name "*.h"`
+        # See if anything changed
+        git diff > /tmp/clang-format.diff
+        cat /tmp/clang-format.diff
+        # Reset for next checkout
+        git checkout .
+        ! test -s /tmp/clang-format.diff
+
+    - name: Pycodestyle
+      run: |
+        set -ex
+        source checkenv/bin/activate
+        # TODO: this probably finds the venv too
+        pycodestyle `find -name "*.py"`
+
+    - name: Shellcheck
+      run: |
+        set -ex
+        # TODO: is this including the venv?
+        shellcheck `find -name "*.sh"`
+
   build:
     runs-on: ubuntu-latest
     strategy:
